
[gcp_service_account]
type = "service_account"
project_id = "tastemap-ai"
private_key_id = "08763ed96cf910916b09b119a2a54360ffa95335"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQDErB5zaIZuGBxH
2BjUjXVkwV6+mNhYNqhlZufnlFgndCzPqV0pA0EWybk0J2p1hTznIQ3nS2RZpbUD
9kLaRFEn1C0xcuEJOgjZU3EPFzYHLFRXLC35l6j3PhzbREcujKqzK5PZ/RMpW0Fh
2cja/9O2qCAzKEHvdfMBDmb1e2UJiatWzyRZG5AepmAkUttEkU3th9ezHmIwXHSr
xRULbn98NXnq6RrwIpNGXTXuEJY+6fqIZNKJrJbFY7GSQ5S0fzpHPep84Y0dugcO
cGlzRpr/wVffNAl6bhk+w52WNuoAuIlji6AFH4Dof2Bsxx5Xks5oRhiWPlda5gWQ
dnS45v2/AgMBAAECggEAMq+RIXkcvB7mmvVsYMscKB1Vx5UonINpnsiIl7w5g+GC
8vnZEorOKYtPect2ulbePUrdhHB/qkL0hdLfo9TbfYJHK2lJ6dDVGv1QM+1tdSfN
jLHMH3kgiKevVCsilTKXg5mFfzajy5LDJO61vwsTiw2FTunfJFGnkOwfSMDGZ1Bp
57flTJhoCn4GYBhin7PgEY1Pv0yAmnDw9Gw9L2uB9v2ryS4nk29vGBQ0/nEFSgrU
O7bLKMRCWW2KaOTy4IU1bLdThZwgiK3oT02WCE8MZzyGGsC9tpblv1R/+mPyrfAP
/pZFaeraatiQhh1UfBIutamvtp61JKwq2QZmzk8ZQQKBgQDoXRvnwkgZkV6CefJR
5w5zF6gaWIUoqsBDn0qptf6iISoyhTGmtHMZ55Egjh+P5NPmuuMTDhFgkHIeOo+f
P9I49b5FK64pX83/CsTvs3f1hq1eVrzVVPdAPKAnGEisKg298WjNnBfhOUcaZzHU
XMzQa3vMAyPvKNBU+iv89AnKrwKBgQDYrZXRHoucGNgtPMf8ljC8/CtxnuwLIKRL
ZqyIrsLfh9p2P+LKkrN3rhvSpO97nq8/sFwVwzdfGthbYHFsakbg+YQ/9seuudpv
LyQx98AGOvN1QS9iHLmAq6ZHAcv4gzt7xXbxU9Ydw5sqqyEGyHFA1OvtM+lVIz3N
XfqvO4OB8QJ/aUnHWzytbuhv6q9XHcWUxpHxmf6CV+sHM5z6N+w/dTeR51JzLRaX
ESXcnOPJaWpGmkYUno3BUgAhtZDTg1Vn7Gdtz+n7AMRokyhOFE8+DAL6i8TBy+i0
IGdYKl7Wjyx/DZJV6tTP/T32+f/IlHF4XPhXIBpMLhJQVDEHvZbW2QKBgGRiz8VJ
7I6OaCFVRqY8gyobfpkucteY8OVKFWdh6EEdtNYSNSV7IBCzpopKBfX1B+Zu88rV
XeL/EfwLy6DaACqdD2t/DvZhftUCNze7O8jnKQJLCAPhoQP/ApNlPrXNPxLR4pBe
MhYqGMqE7FEzLl1GCGQmJ9Vc9XYfM1RaM0xRAoGABkn9ZMElvQglJEThccsu9sdX
rhOocOITDhIUM13yxK0KKb3XfBMB1K/xxY+5V9HSwHjM7P93VdRPzVpoGUSWeDQw
ZZcEGcKI7ERTHwYBTQKHRO2lBLb/ptdL3DBsp+q4Nb0/w6ptEmslZDzi9jSNmgtv
QNL/KE7HtjWK9/mXh60=
-----END PRIVATE KEY-----"""
client_email = "streamlit-app@tastemap-ai.iam.gserviceaccount.com"
client_id = "106894931769217657839"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-app%40tastemap-ai.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


[google]
api_key = "AIzaSyBoaSWCxvXK0I-s4VK5skCN4bbv4YWhaVo" 
[gemini]
api_key = "AIzaSyAyaeM6_7q15JOGxTM2RCR_MStRCjVAhXQ" 